export { default as Main } from './Main';
export { default as Expertise } from './Expertise';
export { default as Project } from './Project';
export { default as People } from './People';
export { default as Contact } from './Contact';
export { default as Navigation } from './Navigation';
export { default as Footer } from './Footer';
export { default as Vision } from './Vision';
export { default as ProjectStrategy } from './ProjectStrategy';